# Generated by Django 4.0.5 on 2022-06-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_linkedin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people_experience',
            old_name='companies',
            new_name='uuid_companies',
        ),
        migrations.RenameField(
            model_name='people_experience',
            old_name='people',
            new_name='uuid_people',
        ),
    ]
