# Generated by Django 4.0.5 on 2022-06-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_linkedin', '0002_rename_companies_people_experience_uuid_companies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people_experience',
            old_name='uuid_companies',
            new_name='companies',
        ),
        migrations.RenameField(
            model_name='people_experience',
            old_name='uuid_people',
            new_name='people',
        ),
    ]
