# Generated by Django 4.0.5 on 2022-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_linkedin', '0006_rename_data_full_loaded_companies_date_full_loaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_size',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='employee_linkedin',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='founded',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='headquarter',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='industry',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
