# Generated by Django 4.0.5 on 2022-06-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_linkedin', '0008_companies_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='countryISO',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
