# Generated by Django 4.0.5 on 2022-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_linkedin', '0009_companies_countryiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='followers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='locationNameGeneral',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='nick',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
